FROM adoptopenjdk/openjdk11:latest
COPY organisation-management-app/build/libs/organisation-management-app-0.0.1-SNAPSHOT.jar /home/organisation-management-app-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","/home/organisation-management-app-0.0.1-SNAPSHOT.jar"]
EXPOSE 8606
#docker run -p 8606 --name usermng userservice
#docker build -t orgservice .
#docker ps -a
#docker rm nume_dreapta
