#docker-compose -f devops/postgres-docker-compose.yml up
version: '2.3'

services:
  mariadb:
    restart: always
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/mariadb/store/:/var/lib/mysql
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=USM
      - POSTGRES_PORT=5432

volumes:
  mariadb:
    driver: local